//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGruppuppgift.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tvdbEntities : DbContext
    {
        public tvdbEntities()
            : base("name=tvdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<personchannel> personchannel { get; set; }
        public virtual DbSet<program> program { get; set; }
    }
}
